export default [
  {
    regNo: 202301,
    role: "Web Development Intern",
    startDate: "16 April 2023",
    endDate: "18 August 2023",
    gender: "Female",
    performance: "Good",
    name: "Khushi Singh",
    awardedOn: "26 August 2023",
    collegeName: "Graphic Era Hill University",
  },
  {
    regNo: 202302,
    role: "Web Development Intern",
    startDate: "14 May 2023",
    endDate: "18 August 2023",
    gender: "Male",
    performance: "Good",
    name: "Yash Kashyap",
    awardedOn: "26 August 2023",
    collegeName: "Graphic Era Hill University",
  },
  {
    regNo: 202303,
    role: "Web Development Intern",
    startDate: "25 June 2023",
    endDate: "31 July 2023",
    gender: "Female",
    performance: "Good",
    name: "Ishika Gupta",
    awardedOn: "1 August 2023",
    collegeName: "College of Technology, Pantnagar",
  },
  {
    regNo: 202304,
    role: "Web Development Intern",
    startDate: "29 May 2023",
    endDate: "31 July 2023",
    gender: "Female",
    performance: "Good",
    name: "Vanshika Gupta",
    awardedOn: "1 August 2023",
    collegeName: "Jaypee Institute of Information Technology",
  },
];
